name: task_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# consider running `flutter pub upgrade --major-versions`. Alternatively,
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #Statemanagement
  flutter_hooks: ^0.20.5

  #Statemanagement and trigger obeservers bloc
  flutter_bloc: ^8.1.5

  #internationalizing and localization
  #dart pub run easy_localization:generate -S assets/translation -f keys -O lib/localization -o locale_keys.g.dart
  easy_localization: ^3.0.7

  #adapting screen and font size
  flutter_screenutil: ^5.9.1

  # parses SVG files
  vector_graphics: ^1.1.11+1

  # A package for creating dynamic forms in your Flutter app.
  flutter_form_builder: ^9.2.1

  # Dependency Injection service locator
  injectable: ^2.3.0

  # widget can help you bring simple yet beautiful skeleton loaders
  shimmer_animation: ^2.1.0+1

  # Dependency Injection service locator
  get_it: ^7.6.0

  # Functional error handling in flutter
  multiple_result: ^5.1.0

  # a package containing annotations for freezed.
  freezed_annotation: ^2.4.1

  # Generating code for JSON serialization and deserialization.
  json_annotation: ^4.9.0

  # A package for mapping data models automatically.
  auto_mappr: ^2.5.0


  # Used to make HTTP requests
  dio: ^5.3.3

  # Dio interceptor that logs network calls in a pretty, easy to read format
  pretty_dio_logger: ^1.3.1

  #Loading animation
  loading_animation_widget: ^1.2.1

  #Load configuration at runtime from a .env file which can be used throughout the application
  flutter_dotenv: ^5.1.0

  # extensible logger which prints beautiful logs.
  logger: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Build Runner is a package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  # Use the below command to generate files:
  # `dart run build_runner build --delete-conflicting-outputs`
  build_runner: ^2.4.1
  # Injectable Generator is a generator for injectable.
  injectable_generator: ^2.4.0
  # Code generator package for freezed
  freezed: ^2.5.2
  # Code generator package for Dart projects which allows you to easily serialize JSON objects.
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^4.0.0
  # parses SVG files
  vector_graphics_compiler: ^1.1.11+1
  # annotation used for AutoMappr code generator.
  auto_mappr_annotation: ^2.2.0



flutter:
  uses-material-design: true

  assets:
    - .env

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
